# Generated by Django 2.2 on 2020-07-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewRentalHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100)),
                ('street_address', models.TextField()),
                ('area', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[(1, 'Lower Silesia'), (2, 'Kujawsko_Pomorskie'), (3, 'Łódź Province'), (4, 'Lublin Province'), (5, 'Lubuskie Province'), (6, 'Małopolska Province'), (7, 'Masovia Province'), (8, 'Opole Province'), (9, 'Podkarpackie Province'), (10, 'Podlasie Province'), (11, 'Pomerania Province'), (12, 'Silesia Province'), (13, 'Holy Cross Province'), (14, 'Warmia_Masuria'), (15, 'Wielkopolska Province'), (16, 'West Pomerania')], max_length=1)),
                ('country', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
    ]
