# Generated by Django 2.2 on 2020-07-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetails',
        ),
    ]
