# Generated by Django 2.2 on 2020-07-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_delete_contactdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrentalhouse',
            name='country',
            field=models.CharField(default='Poland', max_length=100),
        ),
    ]
