# Generated by Django 2.2 on 2020-07-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0003_auto_20200705_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrentalhouse',
            name='house_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='newrentalhouse',
            name='state',
            field=models.CharField(choices=[('1', 'Lower Silesia'), ('2', 'Kujawsko_Pomorskie'), ('3', 'Łódź Province'), ('4', 'Lublin Province'), ('5', 'Lubuskie Province'), ('6', 'Małopolska Province'), ('7', 'Masovia Province'), ('8', 'Opole Province'), ('9', 'Podkarpackie Province'), ('10', 'Podlasie Province'), ('11', 'Pomerania Province'), ('12', 'Silesia Province'), ('13', 'Holy Cross Province'), ('14', 'Warmia_Masuria'), ('15', 'Wielkopolska Province'), ('16', 'West Pomerania')], max_length=1),
        ),
    ]
