# Generated by Django 2.2 on 2020-07-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0006_amenities_househas_preferredtenant_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househas',
            name='basement',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='househas',
            name='bedroom',
            field=models.CharField(choices=[('zero', 0), ('one', 1), ('two', 2), ('three', 3), ('three_plus', 4)], max_length=11),
        ),
        migrations.AlterField(
            model_name='househas',
            name='garden',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='househas',
            name='parking',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='househas',
            name='terrace',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='househas',
            name='wheelchair_accessible',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2),
        ),
    ]
