# Generated by Django 2.2 on 2020-07-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0009_auto_20200715_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrentalhouse',
            name='area',
        ),
        migrations.RemoveField(
            model_name='newrentalhouse',
            name='state',
        ),
    ]
