# Generated by Django 2.2 on 2020-08-16 18:33

from django.db import migrations, models
import renting.models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0011_auto_20200815_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrentalhouse',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=renting.models.house_images),
        ),
    ]
