# Generated by Django 2.2 on 2020-08-20 07:16

from django.db import migrations, models
import django.db.models.deletion
import renting.models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0012_newrentalhouse_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrentalhouse',
            name='images',
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=renting.models.house_images)),
                ('nrh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renting.NewRentalHouse')),
            ],
        ),
    ]
