# Generated by Django 2.2 on 2020-08-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0013_auto_20200820_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetails',
        ),
    ]
