# Generated by Django 2.2 on 2020-08-25 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0014_delete_contactdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrentalhouse',
            name='in_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='newrentalhouse',
            name='out_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
