# Generated by Django 2.2 on 2020-08-30 17:03

from django.db import migrations, models
import renting.models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0017_auto_20200829_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimages',
            name='images',
            field=models.ImageField(blank=True, upload_to=renting.models.house_images),
        ),
    ]
