# Generated by Django 2.2 on 2020-09-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0018_auto_20200830_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='nrh',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='renting.NewRentalHouse'),
        ),
        migrations.AlterField(
            model_name='househas',
            name='nrh',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='renting.NewRentalHouse'),
        ),
        migrations.AlterField(
            model_name='preferredtenant',
            name='nrh',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='renting.NewRentalHouse'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='nrh',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='renting.NewRentalHouse'),
        ),
    ]
